// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

const configFactory = require('./webpack.config.js');
const createDevServerConfig = require('./webpackDevServer.config');

// Load proxy config
const proxyConfig = {
  '/api': {
    target: 'http://localhost:3000',
    pathRewrite: {'^/api' : ''}
  }
};

// Serve webpack assets generated by the compiler over a web server.
const serverConfig = createDevServerConfig(
  proxyConfig,
  '127.0.0.1:4001'
);
const config = configFactory('development');

config.optimization = {
  runtimeChunk: true,
  removeAvailableModules: false,
  removeEmptyChunks: false,
  splitChunks: false,
}
config.devServer = serverConfig

export default config